spring.application.name=VetTurno


spring.datasource.url=jdbc:mysql://localhost:3306/vetturno
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=una_clave_secreta_larga_y_dificil_de_adivinar_cambiala_tu_1234567890
jwt.expiration=86400000
