spring.application.name=AppNotas

spring.mongodb.uri=mongodb+srv://anadevsenior_db_user:4OcSrHoLGSqenRqV@cluster0.skdyiht.mongodb.net/notas_db?appName=Cluster0

jwt.secret=clave-super-secreta-notevault-2026-no-compartir

jwt.expiration=86400000